from collections.abc import Sequence
from typing import Protocol

from aicom.domain.views import ApprovalView, DispatchRef, RunReport


class Notifier(Protocol):
    def send_approval_request(self, view: ApprovalView) -> DispatchRef: ...
    def send_batch_approval_request(
        self, views: Sequence[ApprovalView]
    ) -> DispatchRef: ...
    def send_reminder(self, view: ApprovalView, stage: int) -> None: ...
    def send_run_report(self, report: RunReport) -> None: ...
    def send_system_notice(self, text: str) -> None: ...
