"""initial schema

Revision ID: d7d59d6924a4
Revises: 
Create Date: 2026-08-10 13:25:15.113209

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd7d59d6924a4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('autonomy_level', sa.String(length=32), nullable=False),
    sa.Column('allowed_tools', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('mcp_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workspace_root', sa.String(length=512), nullable=True),
    sa.Column('repo_path', sa.String(length=512), nullable=True),
    sa.Column('max_run_seconds', sa.Integer(), nullable=False),
    sa.Column('max_child_tasks_per_day', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm_paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pause_reason', sa.String(length=200), nullable=True),
    sa.Column('pause_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_pauses', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'BLOCKED', 'DONE', 'FAILED', 'CANCELLED', name='task_status', native_enum=False), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Enum('HUMAN', 'AGENT', name='task_origin', native_enum=False), nullable=False),
    sa.Column('schedule', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'AWAITING_APPROVAL', 'SUCCEEDED', 'FAILED', 'TIMED_OUT', 'CANCELLED', name='run_status', native_enum=False), nullable=False),
    sa.Column('worker_id', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume_pending', sa.Boolean(), nullable=False),
    sa.Column('resume_note', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('token_in', sa.BigInteger(), nullable=False),
    sa.Column('token_out', sa.BigInteger(), nullable=False),
    sa.Column('exit_reason', sa.String(length=40), nullable=True),
    sa.Column('session_id', sa.String(length=120), nullable=True),
    sa.Column('workspace_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_status'), 'run', ['status'], unique=False)
    op.create_index(op.f('ix_run_task_id'), 'run', ['task_id'], unique=False)
    op.create_table('approval',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('SPEND', 'PUBLISH', 'CONTACT', 'EXECUTE_ORDER', name='approval_kind', native_enum=False), nullable=False),
    sa.Column('proposal', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status', native_enum=False), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remind_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remind_count', sa.Integer(), nullable=False),
    sa.Column('last_reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slack_channel', sa.String(length=80), nullable=True),
    sa.Column('slack_ts', sa.String(length=40), nullable=True),
    sa.Column('decided_by', sa.String(length=80), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce')
    )
    op.create_index(op.f('ix_approval_run_id'), 'approval', ['run_id'], unique=False)
    op.create_index(op.f('ix_approval_status'), 'approval', ['status'], unique=False)
    op.create_table('artifact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('git_ref', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_run_id'), 'artifact', ['run_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_event_run_seq')
    )
    op.create_index(op.f('ix_event_run_id'), 'event', ['run_id'], unique=False)
    op.create_table('spend_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approval_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['approval_id'], ['approval.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spend_ledger')
    op.drop_index(op.f('ix_event_run_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_artifact_run_id'), table_name='artifact')
    op.drop_table('artifact')
    op.drop_index(op.f('ix_approval_status'), table_name='approval')
    op.drop_index(op.f('ix_approval_run_id'), table_name='approval')
    op.drop_table('approval')
    op.drop_index(op.f('ix_run_task_id'), table_name='run')
    op.drop_index(op.f('ix_run_status'), table_name='run')
    op.drop_table('run')
    op.drop_table('task')
    op.drop_table('system_state')
    op.drop_table('agent')
    # ### end Alembic commands ###
